# Generated by Django 3.1.7 on 2021-03-02 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('date_of_birth', models.DateField(verbose_name='Date of birth')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=255, verbose_name='email')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Home Address')),
            ],
            options={
                'unique_together': {('first_name', 'last_name', 'date_of_birth', 'address')},
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('date_of_birth', models.DateField(verbose_name='Date of birth')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=255, verbose_name='email')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Home Address')),
                ('reg_number', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Registration Number')),
            ],
            options={
                'unique_together': {('first_name', 'last_name', 'reg_number')},
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prescription_api.doctor')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prescription_api.drug')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prescription_api.pharmacy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prescription_api.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
